apiVersion: v1
kind: Service
metadata:
  name: k8s-sentinel
  namespace: k8s-sentinel
  labels:
    app.kubernetes.io/name: k8s-sentinel
spec:
  type: ClusterIP
  selector:
    app: k8s-sentinel
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
